name: Run OWASP Dependency Check and Retrieve H2 Database

on:
  workflow_dispatch: # Permet un lancement manuel

jobs:
  dependency_check:
    runs-on: ubuntu-latest

    steps:
      # Étape pour vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape pour exécuter OWASP Dependency Check dans Docker
      - name: Run OWASP Dependency Check
        run: |
          docker run -v $(pwd):/src -v $(pwd)/data:/usr/share/dependency-check/data owasp/dependency-check --nvdApiKey 86d18a16-ad6c-4266-afe8-0b959c4fe930 --scan /src
      # Étape pour sauvegarder la base H2 et les rapports générés
      - name: Upload H2 Database and Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-data
          path: ./data
