name: Retrieve Vulnerability Data Mirror

on:
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit UTC
  workflow_dispatch: # Permet d'exécuter manuellement

jobs:
  fetch_vulnerability_data:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_KEY }}
    steps:
      - name: Use secret environment variable
        run: echo "The secret is: $NVD_API_KEY"
      - name: Start Vulnerability Data Mirror
        run: |
          echo "$NVD_API_KEY"
          sudo mkdir /usr/local/odc
          wget https://github.com/jeremylong/open-vulnerability-cli/releases/download/v8.1.0/vulnz-8.1.0.jar
          sudo java -jar vulnz-8.1.0.jar cve --apikey=$NVD_API_KEY --cache --directory=/usr/local/odc

      - name: Save Vulnerability Data
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-data
          path: /usr/local/odc
