name: Run OWASP Dependency Check and Retrieve H2 Database

on:
  workflow_dispatch: # Permet un lancement manuel

jobs:
  dependency_check:
    runs-on: ubuntu-latest

    steps:
      # Étape pour vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape pour exécuter OWASP Dependency Check dans Docker
      - name: Run OWASP Dependency Check
        run: |
          docker run --rm \
          -v $(pwd):/src \
          -v $(pwd)/data:/usr/share/dependency-check/data \
          owasp/dependency-check \
          --init \
          --project "Dependency Check Report" \
          --scan /src \
          --format HTML

      # Étape pour sauvegarder la base H2 et les rapports générés
      - name: Upload H2 Database and Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-data
          path: ./data
