name: Scan CVEs with Vulnz

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vulnz CLI
        run: |
          curl -LO https://github.com/jeremylong/open-vulnerability-cli/archive/refs/tags/V8.1.0.tar.gz
          ls
          file V8.1.0.tar.gz
          tar -xzf V8.1.0.tar.gz
          cd open-vulnerability-cli-8.1.0
          mv open-vulnerability-cli /usr/local/bin/

      - name: Run CVE Scan
        run: vulnz cve --cache --directory ./cache

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-results
          path: ./cache
