name: Retrieve Vulnerability Data Mirror

on:
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit UTC
  workflow_dispatch: # Permet d'exécuter manuellement

jobs:
  fetch_vulnerability_data:
    runs-on: ubuntu-latest
    steps:
      - name: Start Vulnerability Data Mirror
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mkdir /usr/local/odc
          java -jar vulnz-8.1.0.jar cve --apikey=$NVD_API_KEY --cache --directory=/usr/local/odc

      - name: Save Vulnerability Data
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-data
          path: /usr/local/odc
